base_url = "https://enriquekesslerm.com"
title = "enriquekesslerm.com"
compile_sass = true
build_search_index = true
theme = "duckquill"
generate_feed = true
author = "Quique Kessler Martínez"

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"
render_emoji = true
external_links_target_blank = true

[extra]
primary_color = "#fabd2f"
source_url = "https://github.com/Qkessler/enriquekesslerm.com"
issues_url = "https://github.com/Qkessler/enriquekesslerm.com/issues"
date_format = "%F"
stylesheets = [
  "custom.css"
]

[extra.comments]
# Your Mastodon API host; this should be where you have an account
host = "mstdn.social"
# Used to determine who the original/verified poster is;
# role may be expanded in the future (e.g. for moderation).
user = "qkessler"


[extra.nav]
# Display RSS/Atom feed button in the nav
show_feed = true
# Show icons next to links in the nav
icons = true
# Links used in the nav; any icon from https://icons.getbootstrap.com
# can be used as the icon. The bi- prefix should not be added.
links = [
  {url = "/blog", name = "Blog", icon = "journal-bookmark-fill"},
  {url = "/projects", name = "Projects", icon = "motherboard"},
  {url = "/about", name = "About", icon = "person-badge"},
]

[extra.footer]
# "© Title, YEAR" in the footer
show_copyright = true
# Johnvertisement in the footer
show_johnvert = false
# "Powered by Zola and Duckquill" in footer
show_powered_by = true
# Link to website source
show_source = true

[extra.mapbox]
enabled = true

# Default public token on mapbox.
access_token = "pk.eyJ1IjoicWtlc3NsZXIiLCJhIjoiY2xwY3Jta2F1MHNvMTJrcDkwd2VqMmQ2byJ9.iMITWl2u_FynWJjM3Ys05g"
